// ─────────────────────────────────────────────────────────────────────────────
// Mock credentials:
//   SuperAdmin → superadmin@platform.com / admin123
//   Admin tenant → admin@tenant.com / admin123
//
// ⚠️ MOCK ONLY — eliminar cuando se integre el backend real
// ─────────────────────────────────────────────────────────────────────────────

export const MOCK_CREDENTIALS = {
  SUPERADMIN: 'superadmin@platform.com',
  ADMIN: 'admin@tenant.com',
};

// ─────────────────────────────────────────────────────────────────────────────
// Mock: Respuesta del endpoint POST /auth/login
// Tokens válidos hasta 2030 (exp: 1893456000 ≈ 2030-01-01)
// ─────────────────────────────────────────────────────────────────────────────
export const MOCK_LOGIN_RESPONSE = {
  // payload: { sub, type:"access", iat:1740787200, exp:1893456000 }
  accessToken:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc0MDc4NzIwMCwiZXhwIjoxODkzNDU2MDAwfQ.mockAccessSignature123456789',
  // payload: { sub, type:"refresh", iat:1740787200, exp:1893456000, jti }
  refreshToken:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwidHlwZSI6InJlZnJlc2giLCJpYXQiOjE3NDA3ODcyMDAsImV4cCI6MTg5MzQ1NjAwMCwianRpIjoiYjQ1NzYzZTAtYTFlYS00NDg3LTk2ZTItY2JhODkwMTIzNDU2In0.mockRefreshSignature123456789',
};

// ─────────────────────────────────────────────────────────────────────────────
// Mock: SuperAdmin — solo ve módulos de plataforma SaaS
// ─────────────────────────────────────────────────────────────────────────────
export const MOCK_SUPERADMIN_INIT_DATA_RESPONSE = {
  statusCode: 200,
  data: {
    id: 'sa-1',
    names: 'Super Admin',
    email: 'superadmin@platform.com',
    roles: [{ id: 'sa', name: 'superadmin' }],
    modules: [
      {
        moduleId: '6',
        subheader: 'Admin SaaS',
        order: 1,
        items: [
          {
            id: '90',
            name: 'Dashboard',
            icon: 'dashboard',
            path: '/admin/dashboard',
            order: 1,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '6',
            children: [],
          },
          {
            id: '91',
            name: 'Tenants',
            icon: 'tenants',
            path: '/admin/tenants',
            order: 2,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '6',
            children: [],
          },
          {
            id: '92',
            name: 'Planes',
            icon: 'plans',
            path: '/admin/plans',
            order: 3,
            itemparentId: null,
            permissions: ['view', 'edit', 'create'],
            moduleId: '6',
            children: [],
          },
          {
            id: '93',
            name: 'Facturación',
            icon: 'billing',
            path: '/admin/billing',
            order: 4,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '6',
            children: [],
          },
          {
            id: '94',
            name: 'Telemetría',
            icon: 'telemetry',
            path: '/admin/telemetry',
            order: 5,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '6',
            children: [],
          },
        ],
      },
    ],
  },
  message: 'Logged-in user data successfully retrieved',
};

// ─────────────────────────────────────────────────────────────────────────────
// Mock: Admin tenant — acceso completo al CRM (sin módulos de plataforma SaaS)
// ─────────────────────────────────────────────────────────────────────────────
export const MOCK_INIT_DATA_RESPONSE = {
  statusCode: 200,
  data: {
    id: '1',
    names: 'Juan Díaz',
    email: 'admin@tenant.com',
    roles: [{ id: '1', name: 'admin' }],
    modules: [
      {
        moduleId: '1',
        subheader: 'General',
        order: 1,
        items: [
          {
            id: '1',
            name: 'Dashboard',
            icon: 'dashboard',
            path: '/dashboard',
            order: 1,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '1',
            children: [],
          },
        ],
      },
      {
        moduleId: '2',
        subheader: 'Inventario',
        order: 2,
        items: [
          {
            id: '20',
            name: 'Productos',
            icon: 'products',
            path: '/inventory/products',
            order: 2,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '2',
            children: [],
          },
          {
            id: '30',
            name: 'Bodegas',
            icon: 'warehouse',
            path: '/inventory/warehouses',
            order: 3,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '2',
            children: [
              {
                id: '31',
                name: 'Vista General',
                icon: 'overview',
                path: '/inventory/warehouses',
                order: 1,
                itemparentId: '30',
                permissions: ['view'],
                moduleId: '2',
                children: [],
              },
              {
                id: '32',
                name: 'Movimientos',
                icon: 'movements',
                path: '/inventory/warehouses/movements',
                order: 2,
                itemparentId: '30',
                permissions: ['view', 'edit', 'create'],
                moduleId: '2',
                children: [],
              },
            ],
          },
          {
            id: '40',
            name: 'Stock & Disponibilidad',
            icon: 'stock',
            path: '/inventory/stock',
            order: 4,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '2',
            children: [],
          },
        ],
      },
      {
        moduleId: '3',
        subheader: 'Ventas',
        order: 3,
        items: [
          {
            id: '60',
            name: 'Pipeline',
            icon: 'sales',
            path: '/sales/pipeline',
            order: 1,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '3',
            children: [],
          },
          {
            id: '61',
            name: 'Dashboard Financiero',
            icon: 'reports',
            path: '/sales/finance',
            order: 2,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '3',
            children: [],
          },
          {
            id: '62',
            name: 'Cotizaciones',
            icon: 'pricelist',
            path: '/sales/finance/quotation',
            order: 3,
            itemparentId: null,
            permissions: ['view', 'edit', 'create'],
            moduleId: '3',
            children: [],
          },
          {
            id: '65',
            name: 'Facturas',
            icon: 'billing',
            path: '/sales/finance/invoice',
            order: 4,
            itemparentId: null,
            permissions: ['view', 'edit'],
            moduleId: '3',
            children: [],
          },
          {
            id: '63',
            name: 'Reglas de Crédito',
            icon: 'b2b',
            path: '/sales/finance/credit-rules',
            order: 5,
            itemparentId: null,
            permissions: ['view', 'edit'],
            moduleId: '3',
            children: [],
          },
          {
            id: '64',
            name: 'Multimoneda',
            icon: 'Settings',
            path: '/sales/finance/multi-currency',
            order: 6,
            itemparentId: null,
            permissions: ['view', 'edit'],
            moduleId: '3',
            children: [],
          },
        ],
      },
      {
        moduleId: '4',
        subheader: 'Reportes',
        order: 4,
        items: [
          {
            id: '70',
            name: 'Inventario',
            icon: 'LayoutDashboard',
            path: '/reports/inventory',
            order: 1,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '4',
            children: [],
          },
          {
            id: '71',
            name: 'Ventas',
            icon: 'PieChart',
            path: '/reports/sales',
            order: 2,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '4',
            children: [],
          },
        ],
      },
      {
        moduleId: '8',
        subheader: 'CRM',
        order: 8,
        items: [
          {
            id: '110',
            name: 'Directorio',
            icon: 'clients',
            path: '/contacts',
            order: 1,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '8',
            children: [],
          },
          {
            id: '112',
            name: 'Segmentación Dinámica',
            icon: 'Settings',
            path: '/contacts/segments',
            order: 2,
            itemparentId: null,
            permissions: ['view', 'edit', 'create'],
            moduleId: '8',
            children: [],
          },
          {
            id: '111',
            name: 'Agenda & Productividad',
            icon: 'calendar',
            path: '/schedule',
            order: 2,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '8',
            children: [],
          },
        ],
      },
      {
        moduleId: '7',
        subheader: 'Configuración',
        order: 7,
        items: [
          {
            id: '100',
            name: 'Usuarios',
            icon: 'clients',
            path: '/settings/users',
            order: 1,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '7',
            children: [],
          },
          {
            id: '101',
            name: 'Roles y Permisos',
            icon: 'shieldCheck',
            path: '/settings/roles',
            order: 2,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '7',
            children: [],
          },
          {
            id: '102',
            name: 'Equipos y Cartera',
            icon: 'b2b',
            path: '/settings/teams',
            order: 3,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '7',
            children: [],
          },
          {
            id: '103',
            name: 'Campos Personalizados',
            icon: 'Settings',
            path: '/settings/custom-fields',
            order: 4,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '7',
            children: [],
          },
          {
            id: '104',
            name: 'Localización',
            icon: 'Settings',
            path: '/settings/localization',
            order: 5,
            itemparentId: null,
            permissions: ['view', 'edit'],
            moduleId: '7',
            children: [],
          },
          {
            id: '105',
            name: 'Etiquetas (Tags)',
            icon: 'Settings',
            path: '/settings/tags',
            order: 6,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '7',
            children: [],
          },
        ],
      },
      {
        moduleId: '9',
        subheader: 'Proyectos',
        order: 6,
        items: [
          {
            id: '120',
            name: 'Todos los Proyectos',
            icon: 'FolderKanban',
            path: '/projects',
            order: 1,
            itemparentId: null,
            permissions: ['view', 'create', 'edit', 'delete'],
            moduleId: '9',
            children: [],
          },
        ],
      },
      {
        moduleId: '10',
        subheader: 'Canales & Partners',
        order: 9,
        items: [
          {
            id: '130',
            name: 'Partners',
            icon: 'Handshake',
            path: '/partners',
            order: 1,
            itemparentId: null,
            permissions: ['view', 'create', 'edit', 'delete'],
            moduleId: '10',
            children: [],
          },
          {
            id: '131',
            name: 'Oportunidades',
            icon: 'ClipboardList',
            path: '/partners/opportunities',
            order: 2,
            itemparentId: null,
            permissions: ['view', 'create', 'edit'],
            moduleId: '10',
            children: [],
          },
          {
            id: '132',
            name: 'Portal de Materiales',
            icon: 'FolderOpen',
            path: '/partners/portal',
            order: 3,
            itemparentId: null,
            permissions: ['view', 'create'],
            moduleId: '10',
            children: [],
          },
        ],
      },
      {
        moduleId: '5',
        subheader: 'Incentivos y Comisiones',
        order: 5,
        items: [
          {
            id: '81',
            name: 'Planes de Comisión',
            icon: 'Settings',
            path: '/hr/commissions/plans',
            order: 1,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '5',
            children: [],
          },
          {
            id: '82',
            name: 'Asignación a Vendedores',
            icon: 'b2b',
            path: '/hr/commissions/assignment',
            order: 2,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '5',
            children: [],
          },
          {
            id: '83',
            name: 'Mi Dashboard',
            icon: 'dashboard',
            path: '/hr/commissions/dashboard',
            order: 3,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '5',
            children: [],
          },
          {
            id: '84',
            name: 'Simulador',
            icon: 'reports',
            path: '/hr/commissions/simulator',
            order: 4,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '5',
            children: [],
          },
          {
            id: '85',
            name: 'Historial y Liquidación',
            icon: 'table',
            path: '/hr/commissions/history',
            order: 5,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '5',
            children: [],
          },
        ],
      },
      {
        moduleId: '11',
        subheader: 'Inteligencia Competitiva',
        order: 11,
        items: [
          {
            id: '140',
            name: 'Battlecards',
            icon: 'Swords',
            path: '/intelligence/battlecards',
            order: 1,
            itemparentId: null,
            permissions: ['view', 'create', 'edit', 'delete'],
            moduleId: '11',
            children: [],
          },
          {
            id: '141',
            name: 'Razones de Pérdida',
            icon: 'TrendingDown',
            path: '/intelligence/lost-reasons',
            order: 2,
            itemparentId: null,
            permissions: ['view', 'create', 'edit'],
            moduleId: '11',
            children: [],
          },
        ],
      },
      {
        moduleId: '12',
        subheader: 'Automatización',
        order: 12,
        items: [
          {
            id: '150',
            name: 'Reglas',
            icon: 'Zap',
            path: '/automation/rules',
            order: 1,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '12',
            children: [],
          },
          {
            id: '151',
            name: 'Asignación',
            icon: 'UserCheck',
            path: '/automation/assignment',
            order: 2,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '12',
            children: [],
          },
        ],
      },
    ],
  },
  message: 'Logged-in user data successfully retrieved',
};

// ─────────────────────────────────────────────────────────────────────────────
// Selector por credencial — ⚠️ MOCK ONLY
// ─────────────────────────────────────────────────────────────────────────────
export function getMockInitDataByEmail(email: string) {
  if (email === MOCK_CREDENTIALS.SUPERADMIN) {
    return MOCK_SUPERADMIN_INIT_DATA_RESPONSE;
  }
  return MOCK_INIT_DATA_RESPONSE;
}
