// ─────────────────────────────────────────────────────────────────────────────
// Mock: Respuesta del endpoint POST /auth/login
// Tokens válidos hasta 2030 (exp: 1893456000 ≈ 2030-01-01)
// ─────────────────────────────────────────────────────────────────────────────
export const MOCK_LOGIN_RESPONSE = {
  // payload: { sub, type:"access", iat:1740787200, exp:1893456000 }
  accessToken:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwidHlwZSI6ImFjY2VzcyIsImlhdCI6MTc0MDc4NzIwMCwiZXhwIjoxODkzNDU2MDAwfQ.mockAccessSignature123456789',
  // payload: { sub, type:"refresh", iat:1740787200, exp:1893456000, jti }
  refreshToken:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwidHlwZSI6InJlZnJlc2giLCJpYXQiOjE3NDA3ODcyMDAsImV4cCI6MTg5MzQ1NjAwMCwianRpIjoiYjQ1NzYzZTAtYTFlYS00NDg3LTk2ZTItY2JhODkwMTIzNDU2In0.mockRefreshSignature123456789',
};

// ─────────────────────────────────────────────────────────────────────────────
// Mock: Respuesta del endpoint GET /auth/init-data
// ─────────────────────────────────────────────────────────────────────────────
export const MOCK_INIT_DATA_RESPONSE = {
  statusCode: 200,
  data: {
    id: '1',
    names: 'Juan Díaz',
    email: 'juan.diaz@empresa.com',
    roles: [{ id: '1', name: 'admin' }],
    modules: [
      {
        moduleId: '1',
        subheader: 'General',
        order: 1,
        items: [
          {
            id: '1',
            name: 'Dashboard',
            icon: 'dashboard',
            path: '/dashboard',
            order: 1,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '1',
            children: [],
          },
        ],
      },
      {
        moduleId: '2',
        subheader: 'Inventario',
        order: 2,
        items: [
          {
            id: '20',
            name: 'Productos',
            icon: 'products',
            path: '/inventory/products',
            order: 2,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '2',
            children: [],
          },
          {
            id: '30',
            name: 'Bodegas',
            icon: 'warehouse',
            path: '/inventory/warehouses',
            order: 3,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '2',
            children: [
              {
                id: '31',
                name: 'Vista General',
                icon: 'overview',
                path: '/inventory/warehouses',
                order: 1,
                itemparentId: '30',
                permissions: ['view'],
                moduleId: '2',
                children: [],
              },
              {
                id: '32',
                name: 'Movimientos',
                icon: 'movements',
                path: '/inventory/warehouses/movements',
                order: 2,
                itemparentId: '30',
                permissions: ['view', 'edit', 'create'],
                moduleId: '2',
                children: [],
              },
            ],
          },
          {
            id: '40',
            name: 'Stock & Disponibilidad',
            icon: 'stock',
            path: '/inventory/stock',
            order: 4,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '2',
            children: [],
          },
        ],
      },
      {
        moduleId: '3',
        subheader: 'Ventas',
        order: 3,
        items: [
          {
            id: '60',
            name: 'Pipeline',
            icon: 'sales',
            path: '/sales/pipeline',
            order: 1,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '3',
            children: [],
          },
          {
            id: '61',
            name: 'Dashboard Financiero',
            icon: 'reports',
            path: '/sales/finance',
            order: 2,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '3',
            children: [],
          },
          {
            id: '62',
            name: 'Cotizador CPQ',
            icon: 'pricelist',
            path: '/sales/finance/quotation',
            order: 3,
            itemparentId: null,
            permissions: ['view', 'edit', 'create'],
            moduleId: '3',
            children: [],
          },
          {
            id: '63',
            name: 'Reglas de Crédito',
            icon: 'b2b',
            path: '/sales/finance/credit-rules',
            order: 4,
            itemparentId: null,
            permissions: ['view', 'edit'],
            moduleId: '3',
            children: [],
          },
          {
            id: '64',
            name: 'Multimoneda',
            icon: 'Settings',
            path: '/sales/finance/multi-currency',
            order: 5,
            itemparentId: null,
            permissions: ['view', 'edit'],
            moduleId: '3',
            children: [],
          },
        ],
      },
      {
        moduleId: '4',
        subheader: 'Reportes',
        order: 4,
        items: [
          {
            id: '70',
            name: 'Inventario',
            icon: 'LayoutDashboard',
            path: '/reports/inventory',
            order: 1,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '4',
            children: [],
          },
          {
            id: '71',
            name: 'Ventas',
            icon: 'PieChart',
            path: '/reports/sales',
            order: 2,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '4',
            children: [],
          },
        ],
      },
      {
        moduleId: '6',
        subheader: 'Admin SaaS',
        order: 6,
        items: [
          {
            id: '90',
            name: 'Dashboard',
            icon: 'dashboard',
            path: '/admin/dashboard',
            order: 1,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '6',
            children: [],
          },
          {
            id: '91',
            name: 'Tenants',
            icon: 'tenants',
            path: '/admin/tenants',
            order: 2,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '6',
            children: [],
          },
          {
            id: '92',
            name: 'Planes',
            icon: 'plans',
            path: '/admin/planes',
            order: 3,
            itemparentId: null,
            permissions: ['view', 'edit', 'create'],
            moduleId: '6',
            children: [],
          },
          {
            id: '93',
            name: 'Facturación',
            icon: 'billing',
            path: '/admin/facturacion',
            order: 4,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '6',
            children: [],
          },
          {
            id: '94',
            name: 'Telemetría',
            icon: 'telemetry',
            path: '/admin/telemetria',
            order: 5,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '6',
            children: [],
          },
        ],
      },
      {
        moduleId: '8',
        subheader: 'CRM',
        order: 8,
        items: [
          {
            id: '110',
            name: 'Directorio',
            icon: 'clients',
            path: '/contacts',
            order: 1,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '8',
            children: [],
          },
          {
            id: '111',
            name: 'Agenda & Productividad',
            icon: 'calendar',
            path: '/agenda',
            order: 2,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '8',
            children: [],
          },
        ],
      },
      {
        moduleId: '7',
        subheader: 'Configuración',
        order: 7,
        items: [
          {
            id: '100',
            name: 'Usuarios',
            icon: 'clients',
            path: '/settings/users',
            order: 1,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '7',
            children: [],
          },
          {
            id: '101',
            name: 'Roles y Permisos',
            icon: 'shieldCheck',
            path: '/settings/roles',
            order: 2,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '7',
            children: [],
          },
          {
            id: '102',
            name: 'Equipos y Cartera',
            icon: 'b2b',
            path: '/settings/teams',
            order: 3,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '7',
            children: [],
          },
          {
            id: '103',
            name: 'Campos Personalizados',
            icon: 'Settings',
            path: '/settings/custom-fields',
            order: 4,
            itemparentId: null,
            permissions: ['view', 'edit', 'create', 'delete'],
            moduleId: '7',
            children: [],
          },
          {
            id: '104',
            name: 'Localización',
            icon: 'Settings',
            path: '/settings/localization',
            order: 5,
            itemparentId: null,
            permissions: ['view', 'edit'],
            moduleId: '7',
            children: [],
          },
        ],
      },
      {
        moduleId: '5',
        subheader: 'RH',
        order: 5,
        items: [
          {
            id: '80',
            name: 'Incentivos y Comisiones',
            icon: 'sales',
            path: '/rh/comisiones/dashboard',
            order: 1,
            itemparentId: null,
            permissions: ['view'],
            moduleId: '5',
            children: [
              {
                id: '81',
                name: 'Planes de Comisión',
                icon: 'Settings',
                path: '/rh/comisiones/planes',
                order: 1,
                itemparentId: '80',
                permissions: ['view'],
                moduleId: '5',
                children: [],
              },
              {
                id: '82',
                name: 'Asignación a Vendedores',
                icon: 'b2b',
                path: '/rh/comisiones/asignacion',
                order: 2,
                itemparentId: '80',
                permissions: ['view'],
                moduleId: '5',
                children: [],
              },
              {
                id: '83',
                name: 'Mi Dashboard',
                icon: 'dashboard',
                path: '/rh/comisiones/dashboard',
                order: 3,
                itemparentId: '80',
                permissions: ['view'],
                moduleId: '5',
                children: [],
              },
              {
                id: '84',
                name: 'Simulador',
                icon: 'reports',
                path: '/rh/comisiones/simulador',
                order: 4,
                itemparentId: '80',
                permissions: ['view'],
                moduleId: '5',
                children: [],
              },
              {
                id: '85',
                name: 'Historial y Liquidación',
                icon: 'table',
                path: '/rh/comisiones/historial',
                order: 5,
                itemparentId: '80',
                permissions: ['view'],
                moduleId: '5',
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
  message: 'Logged-in user data successfully retrieved',
};
