import type { Contacto } from 'src/features/contacts/types/contacts.types';

export const MOCK_CONTACTOS: Contacto[] = [
  // ── B2B — Empresas ────────────────────────────────────────────────────────
  {
    id: 'c1',
    tipo: 'B2B',
    nombre: 'Constructora Andina S.A.S',
    email: 'contacto@constructoraandina.co',
    telefono: '+57 601 3456789',
    pais: 'Colombia',
    ciudad: 'Bogotá',
    estado: 'ACTIVO',
    nit: '900.123.456-7',
    sector: 'Construcción',
    tamano: 'GRANDE',
    sitioWeb: 'https://constructoraandina.co',
    relaciones: [
      {
        entidadId: 'c4',
        entidadNombre: 'Marta Gómez',
        entidadTipo: 'B2C',
        cargo: 'Directora Comercial',
      },
      {
        entidadId: 'c5',
        entidadNombre: 'Rodrigo Sánchez',
        entidadTipo: 'B2C',
        cargo: 'Gerente de Compras',
      },
    ],
    creadoEn: '2025-01-10T09:00:00Z',
  },
  {
    id: 'c2',
    tipo: 'B2B',
    nombre: 'TechSol México',
    email: 'ventas@techsol.mx',
    telefono: '+52 55 1234 5678',
    pais: 'México',
    ciudad: 'Ciudad de México',
    estado: 'ACTIVO',
    nit: 'TSM850101ABC',
    sector: 'Tecnología',
    tamano: 'MEDIANA',
    sitioWeb: 'https://techsol.mx',
    relaciones: [{ entidadId: 'c6', entidadNombre: 'Ana Ruiz', entidadTipo: 'B2C', cargo: 'CTO' }],
    creadoEn: '2025-02-05T11:00:00Z',
  },
  {
    id: 'c3',
    tipo: 'B2B',
    nombre: 'Distribuidora Los Andes',
    email: 'info@losandes.pe',
    telefono: '+51 1 987 6543',
    pais: 'Perú',
    ciudad: 'Lima',
    estado: 'PROSPECTO',
    nit: '20512345678',
    sector: 'Distribución',
    tamano: 'PEQUENA',
    sitioWeb: undefined,
    relaciones: [],
    creadoEn: '2025-03-01T08:00:00Z',
  },

  // ── B2C — Personas ────────────────────────────────────────────────────────
  {
    id: 'c4',
    tipo: 'B2C',
    nombre: 'Marta Gómez',
    email: 'marta.gomez@constructoraandina.co',
    telefono: '+57 310 987 6543',
    pais: 'Colombia',
    ciudad: 'Bogotá',
    estado: 'ACTIVO',
    cedula: '52.456.789',
    cargo: 'Directora Comercial',
    empresaId: 'c1',
    empresaNombre: 'Constructora Andina S.A.S',
    relaciones: [
      {
        entidadId: 'c1',
        entidadNombre: 'Constructora Andina S.A.S',
        entidadTipo: 'B2B',
        cargo: 'Directora Comercial',
      },
    ],
    creadoEn: '2025-01-15T10:00:00Z',
  },
  {
    id: 'c5',
    tipo: 'B2C',
    nombre: 'Rodrigo Sánchez',
    email: 'rodrigo.sanchez@constructoraandina.co',
    telefono: '+57 315 234 5678',
    pais: 'Colombia',
    ciudad: 'Medellín',
    estado: 'ACTIVO',
    cedula: '71.234.567',
    cargo: 'Gerente de Compras',
    empresaId: 'c1',
    empresaNombre: 'Constructora Andina S.A.S',
    relaciones: [
      {
        entidadId: 'c1',
        entidadNombre: 'Constructora Andina S.A.S',
        entidadTipo: 'B2B',
        cargo: 'Gerente de Compras',
      },
    ],
    creadoEn: '2025-01-20T09:30:00Z',
  },
  {
    id: 'c6',
    tipo: 'B2C',
    nombre: 'Ana Ruiz',
    email: 'ana.ruiz@techsol.mx',
    telefono: '+52 55 9876 5432',
    pais: 'México',
    ciudad: 'Monterrey',
    estado: 'ACTIVO',
    cedula: 'RUMA850510',
    cargo: 'CTO',
    empresaId: 'c2',
    empresaNombre: 'TechSol México',
    relaciones: [
      { entidadId: 'c2', entidadNombre: 'TechSol México', entidadTipo: 'B2B', cargo: 'CTO' },
    ],
    creadoEn: '2025-02-10T14:00:00Z',
  },
  {
    id: 'c7',
    tipo: 'B2C',
    nombre: 'Luis Paredes',
    email: 'luis.paredes@gmail.com',
    telefono: '+51 998 765 432',
    pais: 'Perú',
    ciudad: 'Arequipa',
    estado: 'PROSPECTO',
    cedula: '45678901',
    cargo: 'Propietario',
    empresaId: undefined,
    empresaNombre: undefined,
    relaciones: [],
    creadoEn: '2025-03-10T12:00:00Z',
  },

  // ── B2G — Instituciones ───────────────────────────────────────────────────
  {
    id: 'c8',
    tipo: 'B2G',
    nombre: 'Ministerio de Obras Públicas',
    email: 'contratacion@mop.gob.co',
    telefono: '+57 601 111 2222',
    pais: 'Colombia',
    ciudad: 'Bogotá',
    estado: 'ACTIVO',
    tipoInstitucion: 'Ministerio',
    entidadPublica: true,
    codigoLicitacion: 'LIC-2025-001',
    relaciones: [],
    creadoEn: '2025-01-05T08:00:00Z',
  },
  {
    id: 'c9',
    tipo: 'B2G',
    nombre: 'Alcaldía de Lima',
    email: 'contratos@miraflores.gob.pe',
    telefono: '+51 1 617 7272',
    pais: 'Perú',
    ciudad: 'Lima',
    estado: 'PROSPECTO',
    tipoInstitucion: 'Municipio',
    entidadPublica: true,
    codigoLicitacion: undefined,
    relaciones: [],
    creadoEn: '2025-02-20T10:00:00Z',
  },
];
