// ─── PIPELINE ────────────────────────────────────────────────────────────────

import type {
  PipelineStage,
  Opportunity,
  Quotation,
  Invoice,
} from 'src/features/sales/types/sales.types';

export const PIPELINE_STAGES: PipelineStage[] = [
  { id: 'prospecto', label: 'Prospecto', color: '#F59E0B' },
  { id: 'cotizacion-enviada', label: 'Cotización Enviada', color: '#3B82F6' },
  { id: 'negociacion', label: 'Negociación', color: '#8B5CF6' },
  { id: 'cerrado-ganado', label: 'Cerrado Ganado', color: '#10B981' },
  { id: 'cerrado-perdido', label: 'Cerrado Perdido', color: '#EF4444' },
];

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-001',
    clientName: 'TechMex Solutions',
    contactName: 'Carlos Ruiz',
    contactEmail: 'carlos@techmex.com',
    estimatedAmount: 45200,
    expectedCloseDate: '2026-03-15',
    stage: 'cotizacion-enviada',
    quotationId: 'COT-2024-0089',
    createdAt: '2026-01-10',
    source: 'Web',
    mainProduct: 'Licencias ERP',
    owner: 'María González',
    probability: 60,
    activities: [
      {
        id: 'act-1',
        type: 'reunion',
        date: '2026-03-05T10:00:00Z',
        responsible: 'María González',
        status: 'completada',
        notes: 'Demostración del producto completada con éxito. Cliente solicita cotización.',
      },
      {
        id: 'act-1b',
        type: 'seguimiento',
        date: '2026-04-16T10:00:00Z',
        responsible: 'María González',
        status: 'pendiente',
        notes: 'Seguimiento de cotización enviada. Confirmar si necesitan ajustes.',
      },
    ],
    notes: [
      {
        id: 'note-1',
        content: 'El cliente está creciendo a nivel nacional. Prioridad alta.',
        author: 'María González',
        createdAt: '2026-01-12T14:30:00Z',
      },
    ],
    lastActivityAt: '2026-03-05T10:00:00Z',
    nextActivityAt: '2026-04-16T10:00:00Z',
  },
  {
    id: 'opp-002',
    clientName: 'Global Industries SA',
    contactName: 'Laura Méndez',
    estimatedAmount: 128750,
    expectedCloseDate: '2026-04-01',
    stage: 'negociacion',
    quotationId: 'COT-2024-0088',
    createdAt: '2026-01-08',
    source: 'Evento',
    mainProduct: 'Infraestructura Cloud',
    owner: 'Carlos Ramírez',
    probability: 80,
    activities: [
      {
        id: 'act-2a',
        type: 'reunion',
        date: '2026-04-15T14:00:00Z',
        responsible: 'Carlos Ramírez',
        status: 'pendiente',
        notes: 'Reunión de negociación — presentar contrapropuesta de pricing.',
      },
      {
        id: 'act-2b',
        type: 'llamada',
        date: '2026-04-10T09:00:00Z',
        responsible: 'Carlos Ramírez',
        status: 'pendiente',
        notes: 'Llamada de check-in antes de la reunión.',
      },
    ],
    notes: [],
    lastActivityAt: '2026-02-28T11:00:00Z',
  },
  {
    id: 'opp-003',
    clientName: 'Constructora López',
    estimatedAmount: 87300,
    expectedCloseDate: '2026-03-20',
    stage: 'prospecto',
    quotationId: null,
    createdAt: '2026-01-05',
    source: 'Referido',
    owner: 'Ana Pérez',
    probability: 20,
    activities: [
      {
        id: 'act-3a',
        type: 'email',
        date: '2026-04-17T08:00:00Z',
        responsible: 'Ana Pérez',
        status: 'pendiente',
        notes: 'Enviar presentación corporativa al contacto de compras.',
      },
    ],
    notes: [],
  },
  {
    id: 'opp-004',
    clientName: 'Distribuidora Norte SA',
    estimatedAmount: 32000,
    expectedCloseDate: '2026-02-28',
    stage: 'cerrado-ganado',
    quotationId: 'COT-2024-0075',
    createdAt: '2026-01-02',
    source: 'Email',
    owner: 'María González',
    probability: 100,
    lastActivityAt: '2026-02-25T16:00:00Z',
    activities: [
      {
        id: 'act-opp4-1',
        type: 'reunion',
        date: '2026-02-20T10:00:00Z',
        responsible: 'María González',
        status: 'completada',
        notes: 'Reunión de cierre. Cliente firmó contrato.',
      },
      {
        id: 'act-opp4-2',
        type: 'llamada',
        date: '2026-02-25T16:00:00Z',
        responsible: 'María González',
        status: 'completada',
        notes: 'Llamada de bienvenida post-cierre. Se acordaron fechas de entrega.',
      },
    ],
    notes: [
      {
        id: 'note-opp4-1',
        content: 'Cliente cerrado exitosamente. Factura generada y enviada el 28 de febrero.',
        author: 'María González',
        createdAt: '2026-02-28T09:00:00Z',
      },
    ],
  },
  {
    id: 'opp-005',
    clientName: 'Retail Express Corp',
    estimatedAmount: 19500,
    expectedCloseDate: '2026-02-10',
    stage: 'cerrado-perdido',
    quotationId: 'COT-2024-0071',
    createdAt: '2025-12-20',
    source: 'Facebook Ads',
    owner: 'Carlos Ramírez',
    probability: 0,
    activities: [],
    notes: [],
  },
];

// ─── COTIZACIONES ─────────────────────────────────────────────────────────────

export const MOCK_QUOTATIONS: Quotation[] = [
  {
    id: 'COT-2024-0089',
    opportunityId: 'opp-001',
    client: 'TechMex Solutions',
    priceList: 'B2C - Consumidor Final',
    date: '2026-03-06',
    seller: 'María González',
    status: 'borrador',
    products: [
      {
        id: 'prod-1',
        name: 'Laptop Empresarial Pro 15"',
        sku: 'LAP-PRO-15',
        qty: 2,
        unitPrice: 1299.99,
        discount: 10,
      },
      {
        id: 'prod-2',
        name: 'Monitor UltraWide 34"',
        sku: 'MON-UW-34',
        qty: 3,
        unitPrice: 599.99,
        discount: 5,
      },
      {
        id: 'prod-3',
        name: 'Docking Station USB-C',
        sku: 'DOC-USC-01',
        qty: 1,
        unitPrice: 249.99,
        discount: 0,
      },
    ],
    internalNotes: '',
  },
  {
    id: 'COT-2024-0088',
    opportunityId: 'opp-002',
    client: 'Global Industries SA',
    priceList: 'B2B - Mayorista',
    date: '2026-02-15',
    seller: 'Carlos Ramírez',
    status: 'enviada',
    products: [
      {
        id: 'prod-4',
        name: 'Servidor Rack 2U',
        sku: 'SRV-RACK-2U',
        qty: 1,
        unitPrice: 8500.0,
        discount: 15,
      },
      {
        id: 'prod-5',
        name: 'Switch 48 Puertos PoE',
        sku: 'SWT-48-POE',
        qty: 2,
        unitPrice: 1299.0,
        discount: 10,
      },
    ],
    internalNotes: 'Cliente solicita entrega antes del 15 de abril.',
  },
  {
    id: 'COT-2024-0075',
    opportunityId: 'opp-004',
    client: 'Distribuidora Norte SA',
    priceList: 'B2B - Mayorista',
    date: '2026-02-10',
    seller: 'María González',
    status: 'aprobada',
    products: [
      {
        id: 'prod-dn-1',
        name: 'Software ERP Pyme - Licencia Anual',
        sku: 'ERP-PYME-12M',
        qty: 5,
        unitPrice: 2800.0,
        discount: 10,
      },
      {
        id: 'prod-dn-2',
        name: 'Soporte Técnico Premium',
        sku: 'SOP-PREM-12M',
        qty: 1,
        unitPrice: 6500.0,
        discount: 0,
      },
    ],
    internalNotes: 'Contrato firmado. Factura generada.',
  },
];

// ─── FACTURAS ─────────────────────────────────────────────────────────────────

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'INV-2024-0847',
    quotationId: 'COT-2024-0089',
    client: 'TechMex Solutions',
    clientNif: 'B12345678',
    issueDate: '2026-01-15',
    dueDate: '2026-02-14',
    paymentMethod: 'Transferencia Bancaria',
    seller: 'María González',
    status: 'pendiente',
    total: 4299.94,
    totalPaid: 0,
    products: [
      {
        code: 'LAP-PRO-15',
        name: 'Laptop Empresarial Pro 15"',
        qty: 2,
        unitPrice: 1299.99,
        discount: 10,
        tax: 19,
        subtotal: 2339.98,
      },
      {
        code: 'MON-UW-34',
        name: 'Monitor UltraWide 34"',
        qty: 3,
        unitPrice: 599.99,
        discount: 5,
        tax: 19,
        subtotal: 1709.97,
      },
      {
        code: 'DOC-USC-01',
        name: 'Docking Station USB-C',
        qty: 1,
        unitPrice: 249.99,
        discount: 0,
        tax: 19,
        subtotal: 249.99,
      },
    ],
    payments: [],
  },
  {
    id: 'INV-2024-0075',
    quotationId: 'COT-2024-0075',
    client: 'Distribuidora Norte SA',
    clientNif: 'C98765432',
    issueDate: '2026-02-28',
    dueDate: '2026-03-29',
    paymentMethod: 'Transferencia Bancaria',
    seller: 'María González',
    status: 'pagada',
    total: 19100.0,
    totalPaid: 19100.0,
    products: [
      {
        code: 'ERP-PYME-12M',
        name: 'Software ERP Pyme - Licencia Anual',
        qty: 5,
        unitPrice: 2800.0,
        discount: 10,
        tax: 19,
        subtotal: 12600.0,
      },
      {
        code: 'SOP-PREM-12M',
        name: 'Soporte Técnico Premium',
        qty: 1,
        unitPrice: 6500.0,
        discount: 0,
        tax: 19,
        subtotal: 6500.0,
      },
    ],
    payments: [
      {
        id: 'pay-dn-1',
        date: '2026-03-01',
        method: 'Transferencia Bancaria',
        amount: 19100.0,
        reference: 'TRF-2026-00321',
        status: 'confirmado',
      },
    ],
  },
];
