// ─── PIPELINE ────────────────────────────────────────────────────────────────

import type {
  PipelineStage,
  Opportunity,
  Quotation,
  Invoice,
} from 'src/features/sales/types/sales.types';

export const PIPELINE_STAGES: PipelineStage[] = [
  { id: 'leads', label: 'Leads', color: '#93C5FD' }, // blue-300
  { id: 'contactado', label: 'Contactado', color: '#7DD3FC' }, // sky-300
  { id: 'negociacion', label: 'Negociación', color: '#FCD34D' }, // amber-300
  { id: 'cerrado', label: 'Cerrado', color: '#86EFAC' }, // green-300
];

export const MOCK_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'opp-001',
    clientName: 'TechMex Solutions',
    contactName: 'Carlos Ruiz',
    contactEmail: 'carlos@techmex.com',
    estimatedAmount: 45200,
    expectedCloseDate: '2026-03-15',
    stage: 'contactado',
    quotationId: 'COT-2024-0089',
    createdAt: '2026-01-10',
    stageEnteredAt: '2026-03-06',
    stageHistory: [
      { stage: 'leads', enteredAt: '2026-01-10', exitedAt: '2026-03-06' },
      { stage: 'contactado', enteredAt: '2026-03-06' },
    ],
    checklist: [
      { id: 'chk-001-1', text: 'Contactar al cliente', done: true },
      { id: 'chk-001-2', text: 'Calificar necesidad', done: true },
      { id: 'chk-001-3', text: 'Identificar decisor', done: true },
      { id: 'chk-001-4', text: 'Confirmar presupuesto estimado', done: true },
      { id: 'chk-001-5', text: 'Enviar cotización formal', done: true },
      { id: 'chk-001-6', text: 'Confirmar recepción', done: false },
      { id: 'chk-001-7', text: 'Agendar reunión de revisión', done: false },
    ],
    source: 'Web',
    mainProduct: 'Licencias ERP',
    owner: 'María González',
    probability: 60,
    activities: [
      {
        id: 'act-1',
        type: 'reunion',
        date: '2026-03-05T10:00:00Z',
        responsible: 'María González',
        status: 'completada',
        notes: 'Demostración del producto completada con éxito. Cliente solicita cotización.',
      },
      {
        id: 'act-1b',
        type: 'seguimiento',
        date: '2026-04-16T10:00:00Z',
        responsible: 'María González',
        status: 'pendiente',
        notes: 'Seguimiento de cotización enviada. Confirmar si necesitan ajustes.',
      },
    ],
    notes: [
      {
        id: 'note-1',
        content: 'El cliente está creciendo a nivel nacional. Prioridad alta.',
        author: 'María González',
        createdAt: '2026-01-12T14:30:00Z',
      },
    ],
    lastActivityAt: '2026-03-05T10:00:00Z',
    nextActivityAt: '2026-04-16T10:00:00Z',
  },
  {
    id: 'opp-002',
    clientName: 'Global Industries SA',
    contactName: 'Laura Méndez',
    estimatedAmount: 128750,
    expectedCloseDate: '2026-04-01',
    stage: 'negociacion',
    quotationId: 'COT-2024-0088',
    createdAt: '2026-01-08',
    stageEnteredAt: '2026-02-28',
    stageHistory: [
      { stage: 'leads', enteredAt: '2026-01-08', exitedAt: '2026-02-15' },
      { stage: 'contactado', enteredAt: '2026-02-15', exitedAt: '2026-02-28' },
      { stage: 'negociacion', enteredAt: '2026-02-28' },
    ],
    checklist: [
      { id: 'chk-002-1', text: 'Contactar al cliente', done: true },
      { id: 'chk-002-2', text: 'Calificar necesidad', done: true },
      { id: 'chk-002-3', text: 'Identificar decisor', done: true },
      { id: 'chk-002-4', text: 'Confirmar presupuesto estimado', done: true },
      { id: 'chk-002-5', text: 'Enviar cotización formal', done: true },
      { id: 'chk-002-6', text: 'Agendar reunión de revisión', done: true },
      { id: 'chk-002-7', text: 'Revisar objeciones del cliente', done: true },
      { id: 'chk-002-8', text: 'Ajustar propuesta si aplica', done: false },
      { id: 'chk-002-9', text: 'Confirmar términos', done: false },
      { id: 'chk-002-10', text: 'Obtener aprobación verbal', done: false },
    ],
    source: 'Evento',
    mainProduct: 'Infraestructura Cloud',
    owner: 'Carlos Ramírez',
    probability: 80,
    activities: [
      {
        id: 'act-2a',
        type: 'reunion',
        date: '2026-04-15T14:00:00Z',
        responsible: 'Carlos Ramírez',
        status: 'pendiente',
        notes: 'Reunión de negociación — presentar contrapropuesta de pricing.',
      },
      {
        id: 'act-2b',
        type: 'llamada',
        date: '2026-04-10T09:00:00Z',
        responsible: 'Carlos Ramírez',
        status: 'pendiente',
        notes: 'Llamada de check-in antes de la reunión.',
      },
    ],
    notes: [],
    lastActivityAt: '2026-02-28T11:00:00Z',
  },
  {
    id: 'opp-003',
    clientName: 'Constructora López',
    estimatedAmount: 87300,
    expectedCloseDate: '2026-03-20',
    stage: 'leads',
    quotationId: null,
    createdAt: '2026-01-05',
    stageEnteredAt: '2026-01-05',
    stageHistory: [{ stage: 'leads', enteredAt: '2026-01-05' }],
    checklist: [
      { id: 'chk-003-1', text: 'Contactar al cliente', done: false },
      { id: 'chk-003-2', text: 'Calificar necesidad', done: false },
      { id: 'chk-003-3', text: 'Identificar decisor', done: false },
      { id: 'chk-003-4', text: 'Confirmar presupuesto estimado', done: false },
    ],
    source: 'Referido',
    owner: 'Ana Pérez',
    probability: 20,
    activities: [
      {
        id: 'act-3a',
        type: 'email',
        date: '2026-04-17T08:00:00Z',
        responsible: 'Ana Pérez',
        status: 'pendiente',
        notes: 'Enviar presentación corporativa al contacto de compras.',
      },
    ],
    notes: [],
  },
  {
    id: 'opp-004',
    clientName: 'Distribuidora Norte SA',
    estimatedAmount: 32000,
    expectedCloseDate: '2026-02-28',
    stage: 'cerrado',
    outcome: 'ganado',
    quotationId: 'COT-2024-0075',
    createdAt: '2026-01-02',
    stageEnteredAt: '2026-02-28',
    stageHistory: [
      { stage: 'leads', enteredAt: '2026-01-02', exitedAt: '2026-01-20' },
      { stage: 'contactado', enteredAt: '2026-01-20', exitedAt: '2026-02-10' },
      { stage: 'negociacion', enteredAt: '2026-02-10', exitedAt: '2026-02-28' },
      { stage: 'cerrado', enteredAt: '2026-02-28' },
    ],
    checklist: [
      { id: 'chk-004-1', text: 'Contactar al cliente', done: true },
      { id: 'chk-004-2', text: 'Calificar necesidad', done: true },
      { id: 'chk-004-3', text: 'Enviar cotización formal', done: true },
      { id: 'chk-004-4', text: 'Obtener aprobación verbal', done: true },
      { id: 'chk-004-5', text: 'Enviar contrato final', done: true },
      { id: 'chk-004-6', text: 'Coordinar onboarding', done: true },
    ],
    source: 'Email',
    owner: 'María González',
    probability: 100,
    lastActivityAt: '2026-02-25T16:00:00Z',
    activities: [
      {
        id: 'act-opp4-1',
        type: 'reunion',
        date: '2026-02-20T10:00:00Z',
        responsible: 'María González',
        status: 'completada',
        notes: 'Reunión de cierre. Cliente firmó contrato.',
      },
      {
        id: 'act-opp4-2',
        type: 'llamada',
        date: '2026-02-25T16:00:00Z',
        responsible: 'María González',
        status: 'completada',
        notes: 'Llamada de bienvenida post-cierre. Se acordaron fechas de entrega.',
      },
    ],
    notes: [
      {
        id: 'note-opp4-1',
        content: 'Cliente cerrado exitosamente. Factura generada y enviada el 28 de febrero.',
        author: 'María González',
        createdAt: '2026-02-28T09:00:00Z',
      },
    ],
  },
  {
    id: 'opp-005',
    clientName: 'Retail Express Corp',
    estimatedAmount: 19500,
    expectedCloseDate: '2026-02-10',
    stage: 'cerrado',
    outcome: 'perdido',
    quotationId: 'COT-2024-0071',
    createdAt: '2025-12-20',
    stageEnteredAt: '2026-02-10',
    stageHistory: [
      { stage: 'leads', enteredAt: '2025-12-20', exitedAt: '2026-01-15' },
      { stage: 'contactado', enteredAt: '2026-01-15', exitedAt: '2026-02-10' },
      { stage: 'cerrado', enteredAt: '2026-02-10' },
    ],
    checklist: [
      { id: 'chk-005-1', text: 'Contactar al cliente', done: true },
      { id: 'chk-005-2', text: 'Enviar cotización formal', done: true },
      { id: 'chk-005-3', text: 'Agendar reunión de revisión', done: false },
    ],
    lostReason: {
      category: 'price',
      competitorId: 'comp-01',
      competitorName: 'Odoo Direct',
      detail:
        'El cliente optó por Odoo por ser open source. Precio fue el factor determinante; nuestro TCO fue percibido como alto.',
    },
    source: 'Facebook Ads',
    owner: 'Carlos Ramírez',
    probability: 0,
    activities: [],
    notes: [],
  },
];

// ─── COTIZACIONES ─────────────────────────────────────────────────────────────

export const MOCK_QUOTATIONS: Quotation[] = [
  {
    id: 'COT-2024-0089',
    opportunityId: 'opp-001',
    client: 'TechMex Solutions',
    priceList: 'B2C - Consumidor Final',
    date: '2026-03-06',
    seller: 'María González',
    status: 'borrador',
    products: [
      {
        id: 'prod-1',
        name: 'Laptop Empresarial Pro 15"',
        sku: 'LAP-PRO-15',
        qty: 2,
        unitPrice: 1299.99,
        discount: 10,
      },
      {
        id: 'prod-2',
        name: 'Monitor UltraWide 34"',
        sku: 'MON-UW-34',
        qty: 3,
        unitPrice: 599.99,
        discount: 5,
      },
      {
        id: 'prod-3',
        name: 'Docking Station USB-C',
        sku: 'DOC-USC-01',
        qty: 1,
        unitPrice: 249.99,
        discount: 0,
      },
    ],
    internalNotes: '',
  },
  {
    id: 'COT-2024-0088',
    opportunityId: 'opp-002',
    client: 'Global Industries SA',
    priceList: 'B2B - Mayorista',
    date: '2026-02-15',
    seller: 'Carlos Ramírez',
    status: 'enviada',
    products: [
      {
        id: 'prod-4',
        name: 'Servidor Rack 2U',
        sku: 'SRV-RACK-2U',
        qty: 1,
        unitPrice: 8500.0,
        discount: 15,
      },
      {
        id: 'prod-5',
        name: 'Switch 48 Puertos PoE',
        sku: 'SWT-48-POE',
        qty: 2,
        unitPrice: 1299.0,
        discount: 10,
      },
    ],
    internalNotes: 'Cliente solicita entrega antes del 15 de abril.',
  },
  {
    id: 'COT-2024-0075',
    opportunityId: 'opp-004',
    client: 'Distribuidora Norte SA',
    priceList: 'B2B - Mayorista',
    date: '2026-02-10',
    seller: 'María González',
    status: 'aprobada',
    products: [
      {
        id: 'prod-dn-1',
        name: 'Software ERP Pyme - Licencia Anual',
        sku: 'ERP-PYME-12M',
        qty: 5,
        unitPrice: 2800.0,
        discount: 10,
      },
      {
        id: 'prod-dn-2',
        name: 'Soporte Técnico Premium',
        sku: 'SOP-PREM-12M',
        qty: 1,
        unitPrice: 6500.0,
        discount: 0,
      },
    ],
    internalNotes: 'Contrato firmado. Factura generada.',
  },
];

// ─── FACTURAS ─────────────────────────────────────────────────────────────────

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'INV-2024-0847',
    quotationId: 'COT-2024-0089',
    client: 'TechMex Solutions',
    clientNif: 'B12345678',
    issueDate: '2026-01-15',
    dueDate: '2026-02-14',
    paymentMethod: 'Transferencia Bancaria',
    seller: 'María González',
    status: 'pendiente',
    total: 4299.94,
    totalPaid: 0,
    products: [
      {
        code: 'LAP-PRO-15',
        name: 'Laptop Empresarial Pro 15"',
        qty: 2,
        unitPrice: 1299.99,
        discount: 10,
        tax: 19,
        subtotal: 2339.98,
      },
      {
        code: 'MON-UW-34',
        name: 'Monitor UltraWide 34"',
        qty: 3,
        unitPrice: 599.99,
        discount: 5,
        tax: 19,
        subtotal: 1709.97,
      },
      {
        code: 'DOC-USC-01',
        name: 'Docking Station USB-C',
        qty: 1,
        unitPrice: 249.99,
        discount: 0,
        tax: 19,
        subtotal: 249.99,
      },
    ],
    payments: [],
  },
  {
    id: 'INV-2024-0075',
    quotationId: 'COT-2024-0075',
    client: 'Distribuidora Norte SA',
    clientNif: 'C98765432',
    issueDate: '2026-02-28',
    dueDate: '2026-03-29',
    paymentMethod: 'Transferencia Bancaria',
    seller: 'María González',
    status: 'pagada',
    total: 19100.0,
    totalPaid: 19100.0,
    products: [
      {
        code: 'ERP-PYME-12M',
        name: 'Software ERP Pyme - Licencia Anual',
        qty: 5,
        unitPrice: 2800.0,
        discount: 10,
        tax: 19,
        subtotal: 12600.0,
      },
      {
        code: 'SOP-PREM-12M',
        name: 'Soporte Técnico Premium',
        qty: 1,
        unitPrice: 6500.0,
        discount: 0,
        tax: 19,
        subtotal: 6500.0,
      },
    ],
    payments: [
      {
        id: 'pay-dn-1',
        date: '2026-03-01',
        method: 'Transferencia Bancaria',
        amount: 19100.0,
        reference: 'TRF-2026-00321',
        status: 'confirmado',
      },
    ],
  },
];
